spring.application.name=chargeback

spring.datasource.url=jdbc:postgresql://localhost:5432/chargeback
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=0
spring.rabbitmq.dynamic=true
spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.simple.auto-startup=true
